import inspect
from mcp.server.auth.provider import OAuthAuthorizationServerProvider, AuthorizationParams, OAuthClientInformationFull, OAuthToken, AuthorizationCode, AccessToken, RefreshToken

print("=== OAuthAuthorizationServerProvider ===")
print(inspect.getsource(OAuthAuthorizationServerProvider))
print()
print("=== OAuthClientInformationFull ===")
print(inspect.getsource(OAuthClientInformationFull))
print()
print("=== OAuthToken ===")
print(inspect.getsource(OAuthToken))
print()
print("=== AuthorizationCode ===")
print(inspect.getsource(AuthorizationCode))
print()
print("=== AccessToken ===")
print(inspect.getsource(AccessToken))
print()
print("=== RefreshToken ===")
print(inspect.getsource(RefreshToken))
